language: cpp
compiler: gcc
before_script: test -f test_travis.txt
jobs:
  include:
    - stage: notmain.o
      script: g++ -c Notmain.cpp -o notmain.o
    - stage: main
      script: g++ Main.cpp -o main.o notmain.o
