language: cpp
compiler: gcc

addons:
  apt:
    packages:
      - doxygen

before_script: test -f test_travis.txt

jobs:
  include:
    - script: g++ -c Notmain.cpp -o notmain.o && g++ Main.cpp -o main.out notmain.o && ./main.out
    - script: test -f Doxyfile && sudo mkdir html && sudo doxygen Doxyfile
      after_success:
        - ls
#        - git clone git://pnu-2020102741/test.io.git
#        - cp -f html/ test.io/html
#        - cd test.io
        - git add --all html/
        - git commit -m "Some commit"
#        - git push https://${GITHUB_TOKEN}@github.com/pnu-2020102741/test.io.git
        - git push https://${GITHUB_TOKEN}@github.com/pnu-2020102741/test.io.git HEAD:main
