language: cpp
compiler: gcc
before_script: test -f test_travis.txt
jobs:
  include:
    - stage: notmain.o
      script: g++ Notmain.cpp -c notmain.o
    - stage: main
      script: g++ Main.cpp -o main notmain.o
